--Create Table--
CREATE OR REPLACE TABLE CORE.transactions (
  CUSTOMERID STRING,
  CREDITSCORE INT,
  BALANCE FLOAT,
  ESTIMATEDSALARY FLOAT,
  POINT_EARNED INT,
  FOREIGN KEY (CUSTOMERID) REFERENCES CORE.customers(CUSTOMERID)
);

--Insert Data--
INSERT INTO CORE.transactions
SELECT DISTINCT
  CUSTOMERID,
  CREDITSCORE,
  BALANCE,
  ESTIMATEDSALARY,
  POINT_EARNED
FROM STAGING.cleaned_bank_churn;