--Create Table--
CREATE OR REPLACE TABLE CORE.activity (
  CUSTOMERID STRING,
  TENURE INT,
  ISACTIVEMEMBER INT,
  NUMOFPRODUCTS INT,
  HASCRCARD INT,
  COMPLAIN INT,
  FOREIGN KEY (CUSTOMERID) REFERENCES CORE.customers(CUSTOMERID)
);

--Insert Data--
INSERT INTO CORE.activity
SELECT DISTINCT
  CUSTOMERID,
  TENURE,
  ISACTIVEMEMBER,
  NUMOFPRODUCTS,
  HASCRCARD,
  COMPLAIN
FROM STAGING.cleaned_bank_churn;