--Create Table--
CREATE OR REPLACE TABLE CORE.customers (
  CUSTOMERID STRING PRIMARY KEY,
  GEOGRAPHY STRING,
  GENDER STRING,
  AGE INT,
  CARD_TYPE STRING,
  SATISFACTION_SCORE INT,
  CHURNED INT
);

--Insert Data--
INSERT INTO CORE.customers
SELECT DISTINCT
  CUSTOMERID,
  GEOGRAPHY,
  GENDER,
  AGE,
  CARD_TYPE,
  SATISFACTION_SCORE,
  CHURNED
FROM STAGING.cleaned_bank_churn;